Update check_results

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,8 +64,8 @@ runs:
 
     - name: Commit check errors
       run: |
-        git add --force ${{ steps.chk_results.outputs.report_path }} || echo "No changes to commit"
-        git commit -m 'Add  ${{ steps.chk_results.outputs.error_name }} check file' || echo "No changes to commit"
+        git add --force ${{ steps.check_results.outputs.report_path }} || echo "No changes to commit"
+        git commit -m 'Add  ${{ steps.check_results.outputs.error_name }} check file' || echo "No changes to commit"
         git pull --set-upstream origin 'preview-${{ inputs.pr_num }}' --allow-unrelated-histories --strategy-option=ours
         git push --force origin 'preview-${{ inputs.pr_num }}' || echo "No changes to commit"
       shell: bash
@@ -73,7 +73,7 @@ runs:
     - name: Build components of the spell check comment
       id: build-components
       run: |
-        error_url=https://raw.githubusercontent.com/${{inputs.git_path}}/preview-${{ inputs.pr_num }}/${{ steps.chk_results.outputs.report_path }}
+        error_url=https://raw.githubusercontent.com/${{inputs.git_path}}/preview-${{ inputs.pr_num }}/${{ steps.check_results.outputs.report_path }}
         echo ::set-output name=time::$(date +'%Y-%m-%d')
         echo ::set-output name=commit_id::$inputs.commit_id
         echo ::set-output name=error_url::$error_url
@@ -85,33 +85,33 @@ runs:
       with:
         issue-number: ${{ github.event.pull_request.number }}
         comment-author: 'github-actions[bot]'
-        body-includes: ${{ steps.chk_results.outputs.error_name }}
+        body-includes: ${{ steps.check_results.outputs.error_name }}
 
     - name: There are errors!
-      if: ${{ steps.chk_results.outputs.error_num >= inputs.error_min }}
+      if: ${{ steps.check_results.outputs.error_num >= inputs.error_min }}
       uses: peter-evans/create-or-update-comment@v1
       with:
         comment-id: ${{ steps.fc.outputs.comment-id }}
         issue-number: ${{ github.event.pull_request.number }}
         body: |
-          :warning: ${{ steps.chk_results.outputs.error_name }} :warning:
-          There are ${{ steps.chk_results.outputs.error_name }} that need to be addressed. [Read this guide for more info](https://github.com/jhudsl/OTTR_Template/wiki/Most-common-errors-and-pitfalls#spell-checkurl-checkquiz-format-fail).
+          :warning: ${{ steps.check_results.outputs.error_name }} :warning:
+          There are ${{ steps.check_results.outputs.error_name }} that need to be addressed. [Read this guide for more info](https://github.com/jhudsl/OTTR_Template/wiki/Most-common-errors-and-pitfalls#spell-checkurl-checkquiz-format-fail).
           [Download the errors here.](${{ steps.build-components.outputs.error_url }})
           _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
         edit-mode: replace
 
     - name: Check check results - fail if too many errors
-      if: ${{ steps.chk_results.outputs.error_num >= inputs.error_min }}
+      if: ${{ steps.check_results.outputs.error_num >= inputs.error_min }}
       run: exit 1
       shell: bash
 
     - name: No errors
-      if: ${{ steps.chk_results.outputs.error_num < inputs.error_min }}
+      if: ${{ steps.check_results.outputs.error_num < inputs.error_min }}
       uses: peter-evans/create-or-update-comment@v1
       with:
         comment-id: ${{ steps.fc.outputs.comment-id }}
         issue-number: ${{ github.event.pull_request.number }}
         body: |
-          No ${{ steps.chk_results.outputs.error_name }}! :tada:
+          No ${{ steps.check_results.outputs.error_name }}! :tada:
           _Comment updated at ${{ steps.build-components.outputs.time }} with changes from ${{ steps.build-components.outputs.commit_id }}_
         edit-mode: replace
